[package]
name = "rust-gba-game"
version = "0.1.0"
authors = ["grgr-dkrk <40130327+grgr-dkrk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
