
[tasks.BUILD]
script = ['''
arm-none-eabi-as crt0.s -o target/crt0.o
cargo xbuild --target thumbv4-none-agb.json
arm-none-eabi-objcopy -O binary target/thumbv4-none-agb/debug/rust-gba-game target/rust-gba-game.gba
gbafix target/rust-gba-game.gba
''']